### ISSUE TITLE
Migration causes error

### ISSUE THREAD

**Issue by angusmcleod** [gdpelican/babble#155]
This [migration](https://github.com/gdpelican/babble/blob/master/db/migrate/20151911105850_revert_b0rking_topic_user_migration.rb) causes an error when running ``bundle exec rake db:migrate`` on my local when Babble is installed.

```
uninitialized constant Babble::User/vagrant/plugins/babble/db/migrate/20151911105850_revert_b0rking_topic_user_migration.rb:4:in `up'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in `exec_migration'
/vagrant/lib/freedom_patches/schema_migration_details.rb:7:in `block in exec_migration'
/vagrant/lib/freedom_patches/schema_migration_details.rb:6:in `exec_migration'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `ddl_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in `block in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
NameError: uninitialized constant Babble::User
/vagrant/plugins/babble/db/migrate/20151911105850_revert_b0rking_topic_user_migration.rb:4:in `up'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in `exec_migration'
/vagrant/lib/freedom_patches/schema_migration_details.rb:7:in `block in exec_migration'
/vagrant/lib/freedom_patches/schema_migration_details.rb:6:in `exec_migration'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:1044:in `ddl_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:959:in `block in migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/var/lib/gems/2.2.0/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by gdpelican** [comment]
#156
