### ISSUE TITLE
discourse frontend is down after upgrade on latest branch

### ISSUE THREAD

**Issue by lukasreussner** [gdpelican/babble#208]
@gdpelican 

There seems to be a bug in the latest bubble branch which brings the whole discourse instance down to a blank page. Only the admin/upgrade can be reached.

This is the extract from the Console while trying to load discourse after upgrading to the latest discourse branch (e0803e1)  and babble (c4087ca):

```
    TypeError:     _ember_jquery-37ec894….js:31194 TypeError: this.resource is not a function
            at e.default (http://mydomain.org/assets/plugin-third-party-1bb284d6443fe897b7548529116890b3121016fc8c8e0fbb36ba7642a2341d48.js:1:22315)
            at e.value (http://mydomain.org/assets/application-e137490253132b40420bd6156e1973929d13c3ecb75543e52c38ec8f098d03df.js:8:30503)
            at http://mydomain.org/assets/application-e137490253132b40420bd6156e1973929d13c3ecb75543e52c38ec8f098d03df.js:8:29357
            at Array.forEach (native)
            at n (http://mydomain.org/assets/application-e137490253132b40420bd6156e1973929d13c3ecb75543e52c38ec8f098d03df.js:8:29178)
            at Object.initialize (http://mydomain.org/assets/application-e137490253132b40420bd6156e1973929d13c3ecb75543e52c38ec8f098d03df.js:64:30614)
            at Object.test.n.initialize (http://mydomain.org/assets/application-e137490253132b40420bd6156e1973929d13c3ecb75543e52c38ec8f098d03df.js:1:20341)
            at http://mydomain.org/assets/ember_jquery-37ec8949e7219a8c2b3cdebef9d43bc64a66860ec196f3e10bea842d0296256f.js:5:6683
            at http://mydomain.org/assets/ember_jquery-37ec8949e7219a8c2b3cdebef9d43bc64a66860ec196f3e10bea842d0296256f.js:5:6993
            at Object.t [as default] (http://mydomain.org/assets/ember_jquery-37ec8949e7219a8c2b3cdebef9d43bc64a66860ec196f3e10bea842d0296256f.js:17:28512)
        s	@	_ember_jquery-37ec894….js:31194
        trigger	@	_ember_jquery-37ec894….js:52141
        (anonymous)	@	_ember_jquery-37ec894….js:53392
        invoke	@	_ember_jquery-37ec894….js:343
        flush	@	_ember_jquery-37ec894….js:407
        flush	@	_ember_jquery-37ec894….js:215
        end	@	_ember_jquery-37ec894….js:570
        run	@	_ember_jquery-37ec894….js:692
        join	@	_ember_jquery-37ec894….js:712
        u.join	@	_ember_jquery-37ec894….js:20452
        (anonymous)	@	_ember_jquery-37ec894….js:20515
        l	@	_ember_jquery-37ec894….js:7
        fireWith	@	_ember_jquery-37ec894….js:7
        ready	@	_ember_jquery-37ec894….js:7
        a	@	_ember_jquery-37ec894….js:7
```

**Comment by angusmcleod** [comment]
This is resolved.

https://github.com/gdpelican/babble/commit/b2a319e8e9e587ad32e329d546dea40a440db69c
